# Default values for template-node-typescript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

serviceUrl: "inventory-management-svc-eb:80"

env:
    - name: INGRESS_HOST
      value: {{ include "starter-kit-chart.host" . }}
    - name: PROTOCOLS
      value: {{ include "starter-kit-chart.protocols" . }}
    - name: SERVICE_URL
      value: {{ .Values.serviceUrl | quote }}

replicaCount: 1
logLevel: "debug"

image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent
  port: 3000

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  appid:
    enabled: false
    # web or app - https://cloud.ibm.com/docs/services/appid?topic=appid-kube-auth
    requestType: web

#  host: hello
  namespaceInHost: true
  subdomain: containers.appdomain.cloud
  path: "/"

#  tlsSecretName: ""
